import "../globals.css";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import language from "../../language";
import { notFound } from "next/navigation";
import i18nConfig from "../../../i18nConfig";
import { StoreProvider } from "@/redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LayoutBasic = (props) => {
  const { children, params } = props;
  let messages;
  try {
    messages = language[params.locale];
    if (messages === undefined) {
      //TODO si no existe redireccionar o mandar a la pagina not found pero el root no deja mandar a not found (revisar)
      messages = language[i18nConfig.defaultLocale];
    }
  } catch (error) {
    notFound();
  }
  
  console.log(params.locale)

  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <StoreProvider>{children}</StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default LayoutBasic;
