import 'bootstrap/dist/css/bootstrap.min.css';
import "../../theme/main.scss";
import LayoutBasic from '../layouts/LayoutBasic';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }) {
  return (
    <LayoutBasic
    params={{...params, locale: params.locale}}
    >
      {children}
    </LayoutBasic>
  )
}
